server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventorydb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: inventory-service

#  cloud:
#    consul:
#      discovery:
#        instance-id: ${spring.application.name}:${server.port}:${random.int(1,99)}
#        prefer-ip-address: true
#      host: localhost
#      port: 8500
#      config:
#        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0

