server:
  port: 9090


spring:
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_ADDR:http://localhost:8200}
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        default-context: spring-boot-vault
        backend: microservice-demo
      host: 172.17.0.1
      port: 8200
      scheme: http

  application:
    name: config-server

  config:
    import: optional:vault://

  profiles:
    active: vault

spring-boot-value:
  property: ${demo}


#  main:
#    allow-bean-definition-overriding: true
#  config:
#    import: vault://http://localhost:8204/spring-boot-microservices
#
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  endpoint:
#    env:
#      post:
#        enabled: true