name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    strategy:
      matrix:
        image_name: ["api-gateway", "config-server", "discovery-server", "discovery-server", "inventory-service",
                     "order-service", "product-service"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Build
        working-directory: ${{ matrix.image_name }}
        run: | 
          gradle bootJar
          mv build/libs/$(ls build/libs) app.jar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata for ${{ matrix.image_name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}





